FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY model_artifacts ./model_artifacts

EXPOSE 10000
RUN python -c "import evidently; print('Evidently successfully imported inside Docker build!');"
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "10000"]
